import { dirname } from 'path'
import { fileURLToPath } from 'url'
import { FlatCompat } from '@eslint/eslintrc'

const __filename = fileURLToPath(import.meta.url)
const __dirname  = dirname(__filename)

const compat = new FlatCompat({
  baseDirectory: __dirname,
})

const eslintConfig = [
  // ─── Ignore ──────────────────────────────────────────────────
  {
    ignores: [
      '.next/**',        // Next.js build output (webpack bundles, compiled JS)
      'node_modules/**', // Dependencies
      'out/**',          // Static export output
      'public/**',       // Static assets
      'next-env.d.ts',   // Auto-generated by Next.js — never edit manually
      'scripts/**',      // Plain Node.js utility scripts (CommonJS)
      '*.config.js',
      '*.config.mjs',
      '*.config.ts',
    ],
  },

  // ─── Next.js + TypeScript Regeln ─────────────────────────────
  ...compat.extends('next/core-web-vitals', 'next/typescript'),

  // ─── Custom Overrides ────────────────────────────────────────
  {
    rules: {
      // any[] casts in db.ts sind bewusst gesetzt
      '@typescript-eslint/no-explicit-any': 'warn',
      // Ungenutzte Variablen erlauben wenn mit _ präfixiert
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern:   '^_',
          varsIgnorePattern:   '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
]

export default eslintConfig
